//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogDetails
    {
        public int Id { get; set; }
        public int BlogId { get; set; }
        public string SummartContent { get; set; }
        public string Content { get; set; }
        public Nullable<int> MemberId { get; set; }
    }
}
