//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Images
    {
        public int Id { get; set; }
        public int RefenceTypeId { get; set; }
        public int RefenceId { get; set; }
        public string Path { get; set; }
        public string Description { get; set; }
        public string Link { get; set; }
        public bool IsDefault { get; set; }
    }
}
