//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public Nullable<double> SearchVolume { get; set; }
        public Nullable<double> IsActive { get; set; }
        public Nullable<double> ParentCategoryId { get; set; }
        public Nullable<double> IsHoliday { get; set; }
        public Nullable<double> IsImportant { get; set; }
        public Nullable<double> IsLink { get; set; }
        public Nullable<double> Level { get; set; }
        public Nullable<double> LocLevel1 { get; set; }
        public Nullable<double> LocLevel2 { get; set; }
        public string LocLevel3 { get; set; }
        public string LocLevel4 { get; set; }
        public string LocLevel5 { get; set; }
    }
}
