//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saloons
    {
        public int Id { get; set; }
        public int BussinessId { get; set; }
        public short SaloonTypeId { get; set; }
        public string M2 { get; set; }
    }
}
