//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessNet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VSporEntities : DbContext
    {
        public VSporEntities()
            : base("name=VSporEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlogCategorys> BlogCategorys { get; set; }
        public virtual DbSet<BlogDetails> BlogDetails { get; set; }
        public virtual DbSet<Blogs> Blogs { get; set; }
        public virtual DbSet<BlogSimilars> BlogSimilars { get; set; }
        public virtual DbSet<Business> Business { get; set; }
        public virtual DbSet<Content> Content { get; set; }
        public virtual DbSet<ContentCategory> ContentCategory { get; set; }
        public virtual DbSet<Images> Images { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<MemberRoles> MemberRoles { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<RouteModels> RouteModels { get; set; }
        public virtual DbSet<Saloons> Saloons { get; set; }
        public virtual DbSet<SaloonTypes> SaloonTypes { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<ServicesBusiness> ServicesBusiness { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<WorkerRoles> WorkerRoles { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
        public virtual DbSet<WorkerType> WorkerType { get; set; }
    }
}
