//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workers
    {
        public int Id { get; set; }
        public string TCNo { get; set; }
        public string PassportNo { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Cv { get; set; }
        public int BusinessId { get; set; }
        public string OpenAddress { get; set; }
    }
}
